# Generated by Django 2.1.5 on 2020-06-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pendingres',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pendingres',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='PendingRes',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
