# Generated by Django 2.1.5 on 2020-06-09 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20200609_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='slot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pending', to='reserve.PendingRes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed! Please inform manager on arrival'), (2, 'Manager will ensure that you are in the restaurant. Please wait'), (3, 'Manager has confirmed. Start Ordering now!')], default=1),
        ),
        migrations.AlterField(
            model_name='pendingres',
            name='status',
            field=models.IntegerField(choices=[(1, 'Awaiting confirmation from restaurant'), (2, 'Your reservation request was cancelled by the restaurant')], default=1),
        ),
    ]
