# Generated by Django 2.1.5 on 2020-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_auto_20200609_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='veg',
            field=models.BooleanField(default=True),
        ),
    ]
