# Generated by Django 2.2.13 on 2021-03-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_auto_20200611_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='distance',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
