# Generated by Django 2.2.13 on 2021-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0011_reservation_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='distance',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
