# Generated by Django 2.2.13 on 2021-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0012_auto_20210317_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='distance',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
