# Generated by Django 2.2.13 on 2021-03-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0013_auto_20210317_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='distance',
            new_name='prob',
        ),
    ]
