# Generated by Django 2.2.13 on 2021-03-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0017_dorder_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
